### PR TITLE
Small hack into chease to get it to use our standard xmllib

### PR DESCRIPTION
**Pull request by olivhoenen**
Hi @jlakhlili, 
finally found some time to hack chease to get rid of the conflicting xmllib sources. I was not sure which test program to attempt (calling ets + chease from same program) so I pushed to a separate branch, let you test it, and if it is ok for you, merge it to devel.

### CODE REVIEW

**Comment by jlakhlili** [comment]
Thanks @olivhoenen,
I did a first test and I had a compilation error. It concerns  ''use xml_file_reader'' in the module  chease_standalone.  I will check Include paths in strandalone Makefile and come back to this request.

**Comment by olivhoenen** [comment]
Oh yes we need to modify standalone makefiles, forgot about that, give me 10 minutes I will fix it.

**Comment by olivhoenen** [comment]
Should be ok now, unless I am not building standalone the right way (make standalone MPI=yes?)

**Comment by jlakhlili** [comment]
Yes, it's: 

> make standalone MPI=yes

**Pull request merged**
